### ISSUE TITLE
Question regarding Placeholders in user-data.yaml file

### ISSUE THREAD

**Issue by shantanoo-desai** [mjpitz/rpi-cloud-init#2]
@mjpitz Thank you for this repository, AFAIK there are no substitutions of placeholders e.g. `${HOST}` `${USER}` in `cloud-init`. How are you able to generate the IP addresses and custom users and host names in this repository?

Any information would be helpful.

**Comment by shantanoo-desai** [comment]
I understand, it is possible via `envsubst`. Apologies for opening the issue.

**Comment by mjpitz** [comment]
Hey there! Sorry for the delay. Glad you were able to find what you were looking for! Once upon a time, I had a more in-depth write up in the root of this project that explained the template variables were using `envsubst` so folks didn't need to dig and read a shell script.
